name: CI
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      - name: Xcodebuild Action
        # You may pin to the exact commit or the version.
        # uses: sersoft-gmbh/xcodebuild-action@349a5f8426171a9680acbca22585d2af4c09a5d6
        uses: sersoft-gmbh/xcodebuild-action@v1.6.0
        with:
          project: GoogleInputTools.xcodeproj
          scheme: GoogleInputTools
          configuration: Release
          arch: ${{ matrix.arch }}
          action: build
          use-xcpretty: false

      # Debug step to check build output location
      - name: Debug - List build directory
        run: |
          ls -R build/Release/
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.arch }}
          path: build/Release/
          retention-days: 1

  release:
    needs: build
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      # Create directories
      - name: Create directories
        run: mkdir -p dist/{x86_64,arm64}

      # Download Intel build
      - name: Download x86_64 build
        uses: actions/download-artifact@v4
        with:
          name: build-x86_64
          path: dist/x86_64
          
      # Verify x86_64 download
      - name: Verify x86_64 download
        run: |
          if [ ! -d "dist/x86_64" ] || [ -z "$(ls -A dist/x86_64)" ]; then
            echo "Error: x86_64 build artifacts not found"
            exit 1
          fi

      # Download Apple Silicon build
      - name: Download arm64 build
        uses: actions/download-artifact@v4
        with:
          name: build-arm64
          path: dist/arm64
          
      # Verify arm64 download
      - name: Verify arm64 download
        run: |
          if [ ! -d "dist/arm64" ] || [ -z "$(ls -A dist/arm64)" ]; then
            echo "Error: arm64 build artifacts not found"
            exit 1
          fi

      # Debug step to check downloaded artifacts
      - name: Debug - List dist directory
        run: |
          ls -R dist/

      # Create versioned release tag
      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=release-$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT

      # Archive the builds
      - name: Archive builds
        run: |
          cd dist
          zip -r GoogleInputTools-x86_64.zip x86_64/
          zip -r GoogleInputTools-arm64.zip arm64/
          
      # Verify archives were created
      - name: Verify archives
        run: |
          if [ ! -f "dist/GoogleInputTools-x86_64.zip" ] || [ ! -f "dist/GoogleInputTools-arm64.zip" ]; then
            echo "Error: ZIP archives not created successfully"
            exit 1
          fi

      # Create GitHub release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: Release ${{ steps.tag.outputs.release_tag }}
          body: |
            GoogleInputTools Input Method for macOS
            
            Installation:
            1. Download the appropriate version for your Mac:
               - Intel Macs: GoogleInputTools-x86_64.zip
               - Apple Silicon Macs: GoogleInputTools-arm64.zip
            2. Unzip the file
            3. Copy GoogleInputTools.app to ~/Library/Input Methods/
            4. Log out and log back in
            5. Enable the input method in System Settings > Keyboard > Input Sources
          draft: false
          prerelease: false
          files: |
            ./dist/GoogleInputTools-x86_64.zip
            ./dist/GoogleInputTools-arm64.zip
